server:
  port: 8080

spring:
  application:
    name: mini-commerce-lab

  datasource:
    url: jdbc:postgresql://192.168.56.112:5432/mcl
    username: mcl
    password: mclpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false   # 지금은 DB에 이미 수동으로 적용했으니 일단 꺼두자(혼선 방지)

  kafka:
    bootstrap-servers: 192.168.56.112:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: mcl-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  elasticsearch:
    uris: http://192.168.56.112:9200

  redis:
    host: 192.168.56.112
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [cid=%X{correlationId}] - %msg%n"
